name: Test

on:
  push: null
  pull_request: null
  schedule:
    - cron: '0 12 * * *'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-20.04
            # TODO test non realtime on other platforms
        rust:
          - 1.65.0 # ubuntu 20.04
          - stable
          - nightly
        include:
          - rust: nightly
            cargo_flags: -Z minimal-versions

    runs-on: ${{ matrix.os }}
    steps:
      - run: sudo apt-get install libasound2-dev -y
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            target
          key: ${{ matrix.os }}-${{ matrix.rust }}-${{ matrix.cargo_flags }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.rust }}-${{ matrix.cargo_flags }}-
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: bruxisma/setup-cargo-hack@v1
        with:
          cargo-hack-version: "0.5"
      - name: Build
        run: cargo hack build --feature-powerset ${{ matrix.cargo_flags }}
      - name: Test
        run: cargo hack test --feature-powerset --all-targets --no-fail-fast --workspace --release
      - name: Doc Test
        run: cargo test --all-features --doc --no-fail-fast --workspace
      - name: Build Docs
        run: cargo doc --all-features --workspace 
